"""login lockout

Revision ID: 8d764478ea0f
Revises: ab6e0985534a
Create Date: 2026-07-12 18:16:06.890078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d764478ea0f'
down_revision = 'ab6e0985534a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills the existing rows; they pre-date lockouts, so False.
    with op.batch_alter_table('login_log', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('blocked', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_log', schema=None) as batch_op:
        batch_op.drop_column('blocked')

    # ### end Alembic commands ###
